empower/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maestro/', include('maestro.urls')),
    path('almacen/', include('almacen.urls')),
    path('compras/', include('compras.urls')),
    path('clientes/', include('clientes.urls')),
    path('ventas/', include('ventas.urls')),
    path('finanzas/', include('finanzas.urls')),
]

finanzas/urls.py
# urls.py
from django.urls import path
from finanzas.views import JornadaListView, JornadaDetailView, DetalleJornadaCreateView, JornadaCloseView,\
    JornadaCreateView, CuentaClienteListView, CuentaClienteDetailView, PagoClienteCreateView, CuentaProveedorListView,\
    CuentaProveedorDetailView, PagoProveedorCreateView, VentaPagoView, CompraPagoView, reporte_jornada


urlpatterns = [
    path('jornada', JornadaListView.as_view()),
    path('jornada/<int:pk>/', JornadaDetailView.as_view()),
    path('detallejornada/add/<int:jornada>/', DetalleJornadaCreateView.as_view()),
    path('jornada/close/<int:jornada>/', JornadaCloseView.as_view()),
    path('pagoventa/<int:venta>/', VentaPagoView.as_view()),
    path('pagocompra/<int:compra>/', CompraPagoView.as_view()),
    path('jornada/open/', JornadaCreateView.as_view()),
    path('cuentacliente', CuentaClienteListView.as_view()),
    path('cuentacliente/<int:pk>/', CuentaClienteDetailView.as_view()),
    path('pagocliente/add/<int:cuentacliente>/', PagoClienteCreateView.as_view()),
    path('cuentaproveedor', CuentaProveedorListView.as_view()),
    path('cuentaproveedor/<int:pk>/', CuentaProveedorDetailView.as_view()),
    path('pagoproveedor/add/<int:cuentaproveedor>/', PagoProveedorCreateView.as_view()),
    path('reportjornada/<int:id>', reporte_jornada, name='reportjornada')

]

ventas/urls.py
# urls.py
from django.urls import path
from ventas.views import OfertaListView, OfertaEditView, OfertaDetailView, VentaListView, VentaCreateView,\
    VentaEditView, VentaDetailView, ReporteVentas, VentaEntregaView, VentaCancelarView, VentaDuplicarView,\
    VentaFindView, VentaDescuentoAdicionalView, ReportVentas
from ventas.rviews import ProductoDetailsView, ValidarStockView

app_name = 'ventas'

urlpatterns = [
    path('oferta', OfertaListView.as_view()),
    path('oferta/<int:pk>/', OfertaDetailView.as_view()),
    path('oferta/<int:pk>/edit', OfertaEditView.as_view()),
    path('venta', VentaListView.as_view()),
    path('venta/add', VentaCreateView.as_view()),
    path('find', VentaFindView.as_view()),
    path('venta/<int:pk>/edit', VentaEditView.as_view()),
    path('venta/<int:pk>/', VentaDetailView.as_view()),
    path('venta/<int:venta>/entrega', VentaEntregaView.as_view()),
    path('venta/<int:venta>/cancelar', VentaCancelarView.as_view()),
    path('venta/<int:venta>/duplicar', VentaDuplicarView.as_view()),
    path('detalleventa/<int:pk>/descuento', VentaDescuentoAdicionalView.as_view()),
    path('reporteventas/<int:id>', ReporteVentas, name='reporteventas'),
    path('ventas_reporte/', ReportVentas, name='ventas_reporte'),

    path('api/productodetails/<str:producto>/<int:sucursal>', ProductoDetailsView.as_view()),
    path('api/validatestock/<int:presentacion>/<int:sucursal>/<int:cantidad>', ValidarStockView.as_view()),

]

finanzas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from maestro.models import Caja, Proveedor
from clientes.models import Cliente
from compras.models import Compra
from ventas.models import Venta


class Jornada(models.Model):
    caja = models.ForeignKey(Caja, on_delete=models.PROTECT)
    fechahora_inicio = models.DateTimeField(auto_now_add=True)
    fechahora_fin = models.DateTimeField(null=True, blank=True)
    asignado_inicio = models.ForeignKey(User, on_delete=models.PROTECT, related_name='asignado_inicio', )
    asignado_fin = models.ForeignKey(User, on_delete=models.PROTECT, related_name='asignado_fin', blank=True, null=True)
    monto_actual = models.DecimalField(max_digits=8, decimal_places=2)
    monto_apertura = models.DecimalField(max_digits=8, decimal_places=2)
    monto_cierre = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
    estado = models.BooleanField(default=True)


class DetalleJornada(models.Model):
    TIPO_CHOICES = (
        ('1', 'INGRESO'),
        ('2', 'EGRESO'),
    )
    jornada = models.ForeignKey(Jornada, on_delete=models.PROTECT)
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES)
    is_espontaneo = models.BooleanField(default=False)
    target = models.IntegerField(blank=True, null=True)
    monto = models.DecimalField(max_digits=8, decimal_places=2)
    fechahora = models.DateTimeField(auto_now_add=True)
    descripcion = models.CharField(max_length=250, blank=True, null=True)
    asignado = models.ForeignKey(User, on_delete=models.PROTECT)


class CuentaCliente(models.Model):
    DURACION_CHOICES = (
        ('1', '7 DIAS'),
        ('2', '14 DIAS'),
        ('3', '21 DIAS'),
        ('4', '30 DIAS'),
    )
    ESTADO_CHOICES = (
        ('1', 'PENDIENTE'),
        ('2', 'PAGADO'),
    )
    TIPO_CHOICES = (
        ('1', 'CONTADO'),
        ('2', 'CREDITO'),
    )
    venta = models.ForeignKey(Venta, on_delete=models.PROTECT)
    duracion = models.CharField(max_length=1, choices=DURACION_CHOICES)
    estado = models.CharField(max_length=1, choices=ESTADO_CHOICES)
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES)
    fechahora_caducidad = models.DateTimeField(blank=True, null=True)
    monto_total = models.DecimalField(max_digits=8, decimal_places=2)
    monto_amortizado = models.DecimalField(max_digits=8, decimal_places=2)
    monto_deuda = models.DecimalField(max_digits=8, decimal_places=2)
    cliente = models.ForeignKey(Cliente, on_delete=models.PROTECT)


class PagoCliente(models.Model):
    TIPO_CHOICES = (
        ('1', 'EFECTIVO'),
        ('2', 'DEPOSITO'),
        ('3', 'CHEQUE'),
    )
    BANCO_CHOICES = (
        ('0', 'NO APLICA'),
        ('1', 'BANCO CONTINENTAL'),
        ('2', 'BANCO DE CRÉDITO DEL PERÚ'),
        ('3', 'BANCO DE LA NACIÓN'),
    )
    fechahora = models.DateTimeField(auto_now_add=True)
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES)
    monto = models.DecimalField(max_digits=8, decimal_places=2)
    cuentacliente = models.ForeignKey(CuentaCliente, on_delete=models.PROTECT)
    recibo = models.CharField(max_length=50, blank=True, null=True)
    banco = models.CharField(max_length=1, choices=BANCO_CHOICES, blank=True, null=True)
    codigo = models.CharField(max_length=150, blank=True, null=True)
    asignado = models.ForeignKey(User, on_delete=models.PROTECT)
    venta = models.ForeignKey(Venta, on_delete=models.PROTECT, blank=True, null=True)


class CuentaProveedor(models.Model):
    DURACION_CHOICES = (
        ('1', '7 DIAS'),
        ('2', '14 DIAS'),
        ('3', '21 DIAS'),
        ('4', '30 DIAS'),
    )
    ESTADO_CHOICES = (
        ('1', 'PENDIENTE'),
        ('2', 'PAGADO'),
        ('3', 'CANCELADO'),
    )
    TIPO_CHOICES = (
        ('1', 'CONTADO'),
        ('2', 'CREDITO'),
    )
    compra = models.ForeignKey(Compra, on_delete=models.PROTECT)
    duracion = models.CharField(max_length=1, choices=DURACION_CHOICES)
    estado = models.CharField(max_length=1, choices=ESTADO_CHOICES)
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES)
    fechahora_caducidad = models.DateTimeField()
    monto_total = models.DecimalField(max_digits=8, decimal_places=2)
    monto_amortizado = models.DecimalField(max_digits=8, decimal_places=2)
    monto_deuda = models.DecimalField(max_digits=8, decimal_places=2)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.PROTECT)


class PagoProveedor(models.Model):
    TIPO_CHOICES = (
        ('1', 'EFECTIVO'),
        ('2', 'DEPOSITO'),
        ('3', 'CHEQUE'),
        ('4', 'NOTA CREDITO'),
    )
    BANCO_CHOICES = (
        ('0', 'NO APLICA'),
        ('1', 'BANCO CONTINENTAL'),
        ('2', 'BANCO DE CRÉDITO DEL PERÚ'),
        ('3', 'BANCO DE LA NACIÓN'),
    )
    fechahora = models.DateTimeField(auto_now_add=True)
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES)
    monto = models.DecimalField(max_digits=8, decimal_places=2)
    cuentaproveedor = models.ForeignKey(CuentaProveedor, on_delete=models.PROTECT)
    banco = models.CharField(max_length=1, choices=BANCO_CHOICES)
    codigo = models.CharField(max_length=150)
    recibo = models.CharField(max_length=50)
    asignado = models.ForeignKey(User, on_delete=models.PROTECT)
    compra = models.ForeignKey(Compra, on_delete=models.PROTECT, blank=True, null=True)

finanzas/templates/finanzas/cuentacliente-detail.html
{% extends "finanzas/base.html" %}
{% load static %}

{% load maestro_tags %}

{% block head_files %}
    <link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/css/default/own_replace.css" %}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#modal-pago" class="btn btn-xs btn-primary buttons" data-toggle="modal"><i class="fa fa-dollar-sign"></i></a>
            </div>
            <h4 class="panel-title">Cuenta Cliente</h4>
        </div>
        <div class="panel-body">

             <div class="form-group row m-b-3">
                    <div class="col-md-2">
                        <label class="control-label">CLIENTE:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.cliente.descripcion }}
                    </div>
                    <div class="col-md-2">
                        <label class="control-label">CONDICIÓN:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.get_duracion_display }}
                    </div>
                    <div class="col-md-2">
                        <label class="control-label">ESTADO:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.get_estado_display }}
                    </div>

                </div>
                <div class="form-group row m-b-3">
                    <div class="col-md-2">
                        <label class="control-label">TIPO:</label>
                    </div>
                    <div class="col-md-2" id="orden_total">
                        {{ object.get_tipo_display }}
                    </div>

                    <div class="col-md-2">
                        <label class="control-label">FECHA CADUCIDAD:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.fechahora_caducidad|date:'d-m-Y H:i' }}
                    </div>

                    <div class="col-md-2">
                        <label class="control-label">TOTAL / AMORTIZADO / DEUDA:</label>
                    </div>

                    <div class="col-md-2">
                        {{ object.monto_total }} / {{ object.monto_amortizado }} /  {{ object.monto_deuda}}
                    </div>

                </div>
           <div class="col-md-12">
           
               <legend class="m-b-15">
                   Detalles
               </legend>
               <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Fecha/Hora</th>
                                <th>Tipo</th>
                                <th>Monto</th>
                                <th>Recibo de Pago</th>
                                <th>Banco</th>
                                <th>Codigo</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for d in detalle %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ d.fechahora|date:'d-m-Y H:i' }}</td>
                                        <td>{{ d.get_tipo_display }}</td>
                                        <td>{{ d.monto }}</td>
                                        <td>{{ d.recibo }}</td>
                                        <td>{{ d.get_banco_display }}</td>
                                        <td>{{ d.codigo }}</td>
                                        <td></td>
                                    </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
        </div>
    </div>
    </div>

{% endblock %}


{% block modal %}
    <!-- #modal-dialog -->
    <div class="modal fade" id="modal-pago">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="/finanzas/pagocliente/add/{{ object.id }}/" method="POST">{% csrf_token %}
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Movimiento:</legend>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tipo:</label>
                                {{ pago_create.tipo }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Monto:</label>
                                {{ pago_create.monto }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tipo:</label>
                                {{ pago_create.banco }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Código:</label>
                                {{ pago_create.codigo }}
                            </div>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                        <button type="submit" class="btn btn-success">Crear</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block bottom_scripts %}
            <script src="{% static "assets/plugins/select2/dist/js/select2.min.js" %}"></script>
    <script>
        $(".default-select2").select2({placeholder: 'Seleccione'});
        $(".select2-container--default").removeAttr('style').css("width","100%");
    </script>
{% endblock %}

finanzas/templates/finanzas/cuentacliente-list.html
{% extends "finanzas/base.html" %}
{% load static %}

{% block head_files %}
    <link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />
	<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/plugins/bootstrap-eonasdan-datetimepicker/build/css/bootstrap-datetimepicker.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/css/default/own_replace.css" %}" rel="stylesheet" />
{% endblock %}


{% block content %}
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#modal-filtros" class="btn btn-xs btn-primary buttons" data-toggle="modal"><i class="fa fa-search"></i></a>
            </div>
            <h4 class="panel-title">Cuentas de los Clientes</h4>
        </div>
        <div class="panel-body">
            <table id="table" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th class="text-nowrap">Cliente</th>
                        <th class="text-nowrap">Condición</th>
                        <th class="text-nowrap">Estado</th>
                        <th class="text-nowrap">Tipo</th>
                        <th class="text-nowrap">Vencimiento</th>
                        <th class="text-nowrap">Total</th>
                        <th class="text-nowrap">Amortizado</th>
                        <th class="text-nowrap">Deuda</th>
                        <th class="text-nowrap">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in object_list %}
                        <tr>
                            <td>{{ c.cliente.descripcion }}</td>
                            <td>{{ c.get_duracion_display }}</td>
                            <td>{{ c.get_estado_display }}</td>
                            <td>{{ c.get_tipo_display }}</td>
                            <td>{{ c.fechahora_caducidad|date:'d-m-Y H:i' }}</td>
                            <td>{{ c.monto_total }}</td>
                            <td>{{ c.monto_amortizado }}</td>
                            <td>{{ c.monto_deuda }}</td>
                            <td><div class="fa-2x"><a class="no-link" href="/finanzas/cuentacliente/{{ c.id }}"><i class="fas fa-xs fa-eye icons-table"></i></a></div></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block modal %}
        <!-- #modal-dialog -->
    <div class="modal fade" id="modal-filtros">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="">
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Filtros</legend>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Cliente</label>
                                {{ cuentacliente_filtro.cliente }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Condición</label>
                                {{ cuentacliente_filtro.duracion }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Estado</label>
                                {{ cuentacliente_filtro.estado }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tipo</label>
                                {{ cuentacliente_filtro.tipo }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Fechas</label>
                                <div class="row row-space-12">
                                    <div class="col-xs-8">
                                        {{ cuentacliente_filtro.fechahora_caducidad1 }}
                                    </div>
                                    <div class="col-xs-8">
                                        {{ cuentacliente_filtro.fechahora_caducidad2 }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Monto Amortizado</label>
                                <div class="row row-space-12">
                                    <div class="col-xs-8">
                                        {{ cuentacliente_filtro.monto_amortizado1 }}
                                    </div>
                                    <div class="col-xs-8">
                                        {{ cuentacliente_filtro.monto_amortizado2 }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Monto Total</label>
                                <div class="row row-space-12">
                                    <div class="col-xs-8">
                                        {{ cuentacliente_filtro.monto_amortizado1 }}
                                    </div>
                                    <div class="col-xs-8">
                                        {{ cuentacliente_filtro.monto_amortizado2 }}
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                        <button type="submit" class="btn btn-success">Filtrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block bottom_scripts %}
    <script src="{% static "assets/plugins/DataTables/media/js/jquery.dataTables.js" %}"></script>
	<script src="{% static "assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js" %}"></script>
    <script src="{% static "assets/plugins/select2/dist/js/select2.min.js" %}"></script>
    <script src="{% static "assets/plugins/bootstrap-daterangepicker/moment.js" %}"></script>
    <script src="{% static "assets/plugins/bootstrap-eonasdan-datetimepicker/build/js/bootstrap-datetimepicker.min.js" %}"></script>
    <script>
        $('#table').DataTable({
            language: {
                "url": "/static/assets/plugins/DataTables/language/Spanish.json"
            },
            responsive: true
        });
        $(".default-select2").select2({placeholder: 'Seleccione'});
        $(".multiple-select2").select2();
        $(".select2-container--default").removeAttr('style').css("width","100%");
        $('#fechahora_caducidad1').datetimepicker({format:'DD/MM/YYYY HH:mm'});
        $('#fechahora_caducidad2').datetimepicker({format:'DD/MM/YYYY HH:mm'});
        $("#fechahora_caducidad1").on("dp.change", function (e) {
            $('#fechahora_caducidad2').data("DateTimePicker").minDate(e.date);
        });
        $("#fechahora_caducidad2").on("dp.change", function (e) {
            $('#fechahora_caducidad1').data("DateTimePicker").maxDate(e.date);
        });

    </script>
{% endblock %}

finanzas/templates/finanzas/cuentaproveedor-detail.html
{% extends "finanzas/base.html" %}
{% load static %}

{% load maestro_tags %}

{% block head_files %}
    <link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/css/default/own_replace.css" %}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#modal-pago" class="btn btn-xs btn-primary buttons" data-toggle="modal"><i class="fa fa-dollar-sign"></i></a>
            </div>
            <h4 class="panel-title">Cuenta Proveedor</h4>
        </div>
        <div class="panel-body">

             <div class="form-group row m-b-3">
                    <div class="col-md-2">
                        <label class="control-label">PROVEEDOR:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.proveedor.descripcion }}
                    </div>
                    <div class="col-md-2">
                        <label class="control-label">CONDICIÓN:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.get_duracion_display }}
                    </div>
                    <div class="col-md-2">
                        <label class="control-label">ESTADO:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.get_estado_display }}
                    </div>

                </div>
                <div class="form-group row m-b-3">
                    <div class="col-md-2">
                        <label class="control-label">TIPO:</label>
                    </div>
                    <div class="col-md-2" id="orden_total">
                        {{ object.get_tipo_display }}
                    </div>

                    <div class="col-md-2">
                        <label class="control-label">FECHA CADUCIDAD:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.fechahora_caducidad|date:'d-m-Y H:i' }}
                    </div>

                    <div class="col-md-2">
                        <label class="control-label">TOTAL / AMORTIZADO / DEUDA:</label>
                    </div>

                    <div class="col-md-2">
                        {{ object.monto_total }} / {{ object.monto_amortizado }} /  {{ object.monto_deuda}}
                    </div>

                </div>
           <div class="col-md-12">
           
               <legend class="m-b-15">
                   Detalles
               </legend>
               <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Fecha/Hora</th>
                                <th>Tipo</th>
                                <th>Monto</th>
                                <th>Recibo de Pago</th>
                                <th>Banco</th>
                                <th>Codigo</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for d in detalle %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ d.fechahora|date:'d-m-Y H:i' }}</td>
                                        <td>{{ d.get_tipo_display }}</td>
                                        <td>{{ d.monto }}</td>
                                        <td>{{ d.recibo }}</td>
                                        <td>{{ d.get_banco_display }}</td>
                                        <td>{{ d.codigo }}</td>
                                        <td></td>
                                    </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
        </div>
    </div>
    </div>

{% endblock %}


{% block modal %}
    <!-- #modal-dialog -->
    <div class="modal fade" id="modal-pago">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="/finanzas/pagoproveedor/add/{{ object.id }}/" method="POST">{% csrf_token %}
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Movimiento:</legend>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tipo:</label>
                                {{ pago_create.tipo }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Monto:</label>
                                {{ pago_create.monto }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tipo:</label>
                                {{ pago_create.banco }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Recibo:</label>
                                {{ pago_create.recibo }}
                            </div>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                        <button type="submit" class="btn btn-success">Crear</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block bottom_scripts %}
            <script src="{% static "assets/plugins/select2/dist/js/select2.min.js" %}"></script>
    <script>
        $(".default-select2").select2({placeholder: 'Seleccione'});
        $(".select2-container--default").removeAttr('style').css("width","100%");
    </script>
{% endblock %}