empower/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maestro/', include('maestro.urls')),
    path('almacen/', include('almacen.urls')),
    path('compras/', include('compras.urls')),
    path('clientes/', include('clientes.urls')),
    path('ventas/', include('ventas.urls')),
    path('finanzas/', include('finanzas.urls')),
]

ventas/urls.py
# urls.py
from django.urls import path
from ventas.views import OfertaListView, OfertaEditView, OfertaDetailView, VentaListView, VentaCreateView,\
    VentaEditView, VentaDetailView, ReporteVentas, VentaEntregaView, VentaCancelarView, VentaDuplicarView,\
    VentaFindView, VentaDescuentoAdicionalView, ReportVentas
from ventas.rviews import ProductoDetailsView, ValidarStockView

app_name = 'ventas'

urlpatterns = [
    path('oferta', OfertaListView.as_view()),
    path('oferta/<int:pk>/', OfertaDetailView.as_view()),
    path('oferta/<int:pk>/edit', OfertaEditView.as_view()),
    path('venta', VentaListView.as_view()),
    path('venta/add', VentaCreateView.as_view()),
    path('find', VentaFindView.as_view()),
    path('venta/<int:pk>/edit', VentaEditView.as_view()),
    path('venta/<int:pk>/', VentaDetailView.as_view()),
    path('venta/<int:venta>/entrega', VentaEntregaView.as_view()),
    path('venta/<int:venta>/cancelar', VentaCancelarView.as_view()),
    path('venta/<int:venta>/duplicar', VentaDuplicarView.as_view()),
    path('detalleventa/<int:pk>/descuento', VentaDescuentoAdicionalView.as_view()),
    path('reporteventas/<int:id>', ReporteVentas, name='reporteventas'),
    path('ventas_reporte/', ReportVentas, name='ventas_reporte'),

    path('api/productodetails/<str:producto>/<int:sucursal>', ProductoDetailsView.as_view()),
    path('api/validatestock/<int:presentacion>/<int:sucursal>/<int:cantidad>', ValidarStockView.as_view()),

]

ventas/models.py
from django.db import models
from maestro.models import Sucursal, TipoComprobante, Producto, PresentacionxProducto, Impuesto
from clientes.models import Cliente
from django.contrib.auth.models import User


# Create your models here.
class Venta(models.Model):
    ESTADO_ENVIO_CHOICES = (
        ('1', 'GENERADO'),
        # ('2', 'CONVERTIDO A PEDIDO'),
        ('3', 'VENTA'),
        ('4', 'ANULADO'),
        ('5', 'OCUPADO'),
    )
    ESTADO_PAGO_CHOICES = (
        ('1', 'EN DEUDA'),
        ('2', 'PAGADO'),
    )
    TIPO_PAGO_CHOICES = (
        ('1', 'CONTADO'),
        ('2', 'CREDITO'),
    )
    TIPO_CHOICES = (
        ('1', 'VENTA DIRECTA'),
        ('2', 'PROFORMA'),
    )
    asignado = models.ForeignKey(User, on_delete=models.PROTECT)
    cliente = models.ForeignKey(Cliente, on_delete=models.PROTECT, null=True, blank=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.PROTECT)
    estado = models.CharField(max_length=1, choices=ESTADO_ENVIO_CHOICES, default=1)
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES, default=1)
    tipo_pago = models.CharField(max_length=1, choices=TIPO_PAGO_CHOICES, default=1)
    estado_pago = models.CharField(max_length=1, choices=ESTADO_PAGO_CHOICES, default=1)
    fechahora_creacion = models.DateTimeField(auto_now_add=True)
    tipo_comprobante = models.ForeignKey(TipoComprobante, on_delete=models.PROTECT, null=True, blank=True)
    serie_comprobante = models.CharField(max_length=10, null=True, blank=True)
    numero_comprobante = models.CharField(max_length=10, null=True, blank=True)
    sub_total = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    descuento = models.DecimalField(max_digits=8, decimal_places=2, default=0, blank=True, null=True)
    impuesto_monto = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    descuento_adicional = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    total_final = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    total_con_descuento = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    is_pagado = models.BooleanField(default=False)
    is_entregado = models.BooleanField(default=False)


class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT)
    presentacionxproducto = models.ForeignKey(PresentacionxProducto, on_delete=models.PROTECT)
    cantidad_presentacion_pedido = models.IntegerField(blank=True, null=True)
    cantidad_presentacion_entrega = models.IntegerField(blank=True, null=True)
    cantidad_unidad_pedido = models.IntegerField(blank=True, null=True)
    cantidad_unidad_entrega = models.IntegerField(blank=True, null=True)
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    sub_total = models.DecimalField(max_digits=8, decimal_places=2)
    descuento = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    impuesto = models.ManyToManyField(Impuesto)
    impuesto_monto = models.DecimalField(max_digits=8, decimal_places=2)
    total = models.DecimalField(max_digits=8, decimal_places=2)
    descuento_adicional = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    total_final = models.DecimalField(max_digits=8, decimal_places=2)
    total_con_descuento = models.DecimalField(max_digits=8, decimal_places=2)
    is_oferta = models.BooleanField(default=False)
    is_nodeseado = models.BooleanField(default=True)
    is_checked = models.BooleanField(default=False)


class OfertaVenta(models.Model):
    TIPO_DURACION_CHOICES = (
        ('1', 'TEMPORAL'),
        ('2', 'PERMANENTE'),
    )
    TIPO_CHOICES = (
        ('1', 'PRODUCTO'),
        ('2', 'DESCUENTO MONETARIO'),
        ('3', 'DESCUENTO PORCENTUAL'),
    )
    is_active = models.BooleanField(default=True)
    estado = models.BooleanField(default=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.PROTECT)
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES)
    tipo_duracion = models.CharField(max_length=1, choices=TIPO_DURACION_CHOICES)
    producto_oferta = models.ForeignKey(Producto, on_delete=models.PROTECT, related_name='producto_oferta_venta')
    presentacion_oferta = models.ForeignKey(PresentacionxProducto, on_delete=models.PROTECT,
                                            related_name='presentacion_oferta_venta')
    cantidad_oferta = models.IntegerField()
    cantidad_unidad_oferta = models.IntegerField(blank=True, null=True)
    producto_retorno = models.ForeignKey(Producto, on_delete=models.PROTECT, blank=True, null=True,
                                         related_name='producto_retorno_venta')
    presentacion_retorno = models.ForeignKey(PresentacionxProducto, on_delete=models.PROTECT,
                                             related_name='presentacion_retorno_venta', blank=True, null=True)
    retorno = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    fechahora_inicio = models.DateTimeField(blank=True, null=True)
    fechahora_fin = models.DateTimeField(blank=True, null=True)
    stock_limite = models.IntegerField(blank=True, null=True)
    stock_faltante = models.IntegerField(blank=True, null=True)

ventas/views.py
from django.views.generic import DetailView, ListView, TemplateView, RedirectView, UpdateView
from django.shortcuts import redirect, HttpResponse
import json
# Mixin Import-->
from maestro.mixin import BasicEMixin
# Mixin Import<--

# Extra python features-->
from datetime import datetime
# Extra python features<--

from .utils import fill_data_venta, load_tax, create_venta_txt, cancelarventa
from maestro.utils import empresa_list

# Model import-->
from ventas.models import OfertaVenta, Venta, DetalleVenta
from finanzas.models import Jornada
# Model import<--

# Forms import-->
from .forms import OfertaVentaForm, VentaFiltroForm, VentaCreateForm, VentaEditForm, DetalleVentaForm, ImpuestoForm,\
    VentaDescuentoAdicionalForm
from finanzas.forms import PagoVentaForm
# Forms import<--
from openpyxl.styles import Border, Side
from openpyxl import Workbook, load_workbook


# Create your views here.
class OfertaListView(BasicEMixin, ListView):

    template_name = 'ventas/oferta-list.html'
    model = OfertaVenta
    nav_name = 'nav_oferta'
    view_name = 'oferta_venta'
    action_name = 'leer'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        categorias = self.request.GET.getlist('categoria')
        if len(categorias) > 0:
            query = OfertaVenta.objects.filter(categorias__in=categorias)
        else:
            query = OfertaVenta.objects.all()
        query = query.filter(sucursal__empresa__in=empresa_list(self.request.user))
        return query


class OfertaDetailView(BasicEMixin, DetailView):

    template_name = 'ventas/oferta-detail.html'
    model = OfertaVenta
    nav_name = 'nav_oferta'
    view_name = 'oferta_venta'
    action_name = 'leer'


class OfertaEditView(BasicEMixin, TemplateView):

    template_name = 'ventas/oferta-edit.html'
    nav_name = 'nav_oferta'
    view_name = 'oferta_venta'
    action_name = 'editar'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs['pk'] == 0:
                context['object'] = OfertaVentaForm(user=self.request.user)
        else:
            producto = OfertaVenta.objects.get(pk=self.kwargs['pk'])
            context['object'] = OfertaVentaForm(instance=producto, user=self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        if self.kwargs['pk'] == 0:
            form = OfertaVentaForm(request.POST, user=self.request.user)
        else:
            producto = OfertaVenta.objects.get(pk=self.kwargs['pk'])
            form = OfertaVentaForm(request.POST, instance=producto, user=self.request.user)
        if form.is_valid():
            oferta = form.save(commit=False)
            if oferta.stock_faltante is None:
                oferta.stock_faltante = oferta.stock_limite
            oferta.save()
        else:
            return HttpResponse(form.errors)
        return redirect('/ventas/oferta/' + str(oferta.id))


class VentaListView(BasicEMixin, ListView):

    template_name = 'ventas/venta-list.html'
    model = Venta
    nav_name = 'nav_venta'
    view_name = 'venta'
    action_name = 'leer'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['venta_filtro'] = VentaFiltroForm(self.request.GET, user=self.request.user)
        context['venta_create'] = VentaCreateForm(user=self.request.user)
        return context

    def get_queryset(self):
        alt = 0
        query = super().get_queryset()
        cliente = self.request.GET.getlist('cliente')
        sucursal = self.request.GET.getlist('sucursal')
        estado = self.request.GET.getlist('estado')
        tipo_pago = self.request.GET.getlist('tipo_pago')
        estado_pago = self.request.GET.getlist('estado_pago')
        if len(cliente) > 0:
            alt += 1
            query = query.filter(cliente__in=cliente)
        if len(sucursal) > 0:
            alt += 1
            query = query.filter(sucursal__in=sucursal)
        if len(estado) > 0:
            alt += 1
            query = query.filter(estado__in=estado)
        if len(tipo_pago) > 0:
            alt += 1
            query = query.filter(tipo_pago__in=tipo_pago)
        if len(estado_pago) > 0:
            alt += 1
            query = query.filter(estado_pago__in=estado_pago)
        if 'fechahora_creacion1' in self.request.GET and 'fechahora_creacion2' in self.request.GET:
            if self.request.GET['fechahora_creacion1'] != '' and self.request.GET['fechahora_creacion2'] != '':
                alt += 1
                fecha_inicio = datetime.strptime(self.request.GET['fechahora_creacion1'], '%d/%m/%Y %H:%M')
                fecha_fin = datetime.strptime(self.request.GET['fechahora_creacion2'], '%d/%m/%Y %H:%M')
                query = query.filter(fechahora_creacion__gte=fecha_inicio, fechahora_creacion__lte=fecha_fin)
        if 'total1' in self.request.GET or 'total2' in self.request.GET:
            total1 = self.request.GET['total1']
            total2 = self.request.GET['total2']
            if total1 != '' and total2 != '':
                alt += 1
                query = query.filter(total__gte=total1, total__lte=total2)
            elif total1 == '' and total2 != '':
                alt += 1
                query = query.filter(total__lte=total2)
            elif total2 == '' and total1 != '':
                alt += 1
                query = query.filter(total__gte=total1)
        if alt == 0:
            query = Venta.objects.filter(estado__in=[1, 2])
        query = query.filter(sucursal__empresa__in=empresa_list(self.request.user))
        return query


class VentaCreateView(BasicEMixin, RedirectView):

    url = '/ventas/venta/'
    view_name = 'venta'
    action_name = 'crear'

    def get_redirect_url(self, *args, **kwargs):
        form = VentaCreateForm(self.request.POST, user=self.request.user)
        if form.is_valid():
            jornada = Jornada.objects.filter(estado=True)
            if len(jornada) > 0:
                if form.cleaned_data['cliente'] is not None:
                    try:
                        venta = Venta.objects.get(cliente=form.cleaned_data['cliente'], estado=1)
                    except Venta.DoesNotExist:
                        venta = form.save(commit=False)
                        venta.asignado = self.request.user
                        venta.save()
                else:
                    venta = form.save(commit=False)
                    venta.asignado = self.request.user
                    venta.save()
                url = self.url + str(venta.id) + '/edit'
            else:
                url = '/ventas/venta'
        else:
            url = '/ventas/venta'
        return url


class VentaDuplicarView(BasicEMixin, RedirectView):

    url = '/ventas/venta/'
    view_name = 'venta'
    action_name = 'crear'

    def get_redirect_url(self, *args, **kwargs):
        venta = Venta.objects.get(pk=self.kwargs['venta'])
        detalleventa = DetalleVenta.objects.filter(venta=venta.id, is_oferta=False)
        venta.estado = '1'
        venta.pk = None
        venta.save()
        for d in detalleventa:
            d.pk = None
            d.venta = venta
            d.save()
        url = self.url + str(venta.id) + '/edit'
        return url


class VentaDescuentoAdicionalView(BasicEMixin, UpdateView):

    form_class = VentaDescuentoAdicionalForm
    model = DetalleVenta
    success_url = '/ventas/venta/'
    view_name = 'venta'
    action_name = 'descuento_adicional'

    def form_valid(self, form):
        detalleventa = form.save(commit=False)
        if not detalleventa.venta.is_pagado:
            detalleventa.total_con_descuento -= detalleventa.descuento_adicional
            detalleventa.save()
            venta = detalleventa.venta
            venta.descuento += detalleventa.descuento_adicional
            venta.total_con_descuento -= detalleventa.descuento_adicional
            venta.save()
        return super().form_valid(form)

    def get_success_url(self):
        url = self.success_url + str(self.object.venta.id)
        return url


class VentaEditView(BasicEMixin, TemplateView):

    template_name = 'ventas/venta-edit.html'
    nav_name = 'nav_venta'
    view_name = 'venta'
    action_name = 'editar'

    def dispatch(self, request, *args, **kwargs):
        venta = Venta.objects.get(pk=self.kwargs['pk'])
        if venta.estado != '1':
            return redirect('/ventas/venta/' + str(venta.id))
        else:
            return super().dispatch(request)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        venta = Venta.objects.get(pk=self.kwargs['pk'])
        context['form'] = VentaEditForm(instance=venta, user=self.request.user)
        context['impuesto_form'] = ImpuestoForm()
        context['model'] = venta
        detalle = DetalleVenta.objects.filter(venta=self.kwargs['pk'], is_oferta=False)
        content_detalle = []
        for idx, d in enumerate(detalle):
            d = load_tax(d)
            content_detalle.append([DetalleVentaForm(instance=d, prefix='dv'+str(idx+1),
                                                     sucursal=venta.sucursal_id, has_data=True), d])
        context['detalle'] = content_detalle
        context['clean_form'] = DetalleVentaForm(sucursal=venta.sucursal_id, has_data=False)
        return context

    def post(self, request, *args, **kwargs):
        venta = Venta.objects.get(pk=self.kwargs['pk'])
        form = VentaEditForm(request.POST, instance=venta, user=self.request.user)
        incidencias = []
        if form.is_valid():
            venta = form.save()
            DetalleVenta.objects.filter(venta=venta.id, is_oferta=True).delete()
            if request.POST['detalleventa_to_save'] != '':
                total = 0

ventas/templates/ventas/venta-list.html
{% extends "ventas/base.html" %}
{% load static %}

{% block head_files %}
    <link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />
	<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/plugins/bootstrap-eonasdan-datetimepicker/build/css/bootstrap-datetimepicker.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/css/default/own_replace.css" %}" rel="stylesheet" />
{% endblock %}


{% block content %}
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#modal-crear" data-toggle="modal" class="btn btn-xs btn-primary buttons"><i class="fa fa-plus"></i></a>
                <a href="#modal-filtros" class="btn btn-xs btn-primary buttons" data-toggle="modal"><i class="fa fa-search"></i></a>  
               <!--  <a  href="/compras/reportes" id="btnExport" class="btn btn-xs btn-primary buttons no-link"><i class="fa fa-search"></i>Reporte</a>       -->
                <button type="submit" form="reporte" class="btn btn-xs btn-success buttons"><i class="far fa-file-excel"></i></button>

            </div>
            <h4 class="panel-title">Venta</h4>
        </div>
        <div class="panel-body">
           
            <table id="table" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th class="text-nowrap">Cliente</th>
                        <th class="text-nowrap">Sucursal</th>
                        <th class="text-nowrap">Asignado</th>
                        <th class="text-nowrap">Estado</th>
                        <th class="text-nowrap">Pago</th>
                        <th class="text-nowrap">Total</th>
                        <th class="text-nowrap">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for o in object_list %}
                        <tr>
                            <td>{{ o.cliente.descripcion|default:'REGULAR' }}</td>
                            <td>{{ o.sucursal.descripcion }}</td>
                            <td>{{ o.asignado.username }}</td>
                            <td>{{ o.get_estado_display }}</td>
                            <td>{{ o.get_tipo_pago_display }}</td>
                            <td>{{ o.total_con_descuento }}</td>
                            <td><div class="fa-2x"><a class="no-link" href="/ventas/venta/{{ o.id }}"><i class="fas fa-xs fa-eye icons-table"></i></a><a class="no-link" href="/ventas/venta/{{ o.id }}/edit"><i  class="fas fa-xs fa-edit icons-table"></i></a></div></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block modal %}
    <!-- #modal-dialog -->
    <div class="modal fade" id="modal-filtros">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="">
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Filtros</legend>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Cliente</label>
                                {{ venta_filtro.cliente }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Sucursal</label>
                                {{ venta_filtro.sucursal }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Estado</label>
                                {{ venta_filtro.estado }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tipo Pago</label>
                                {{ venta_filtro.tipo_pago }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Estado Pago</label>
                                {{ venta_filtro.estado_pago }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Fechas</label>
                                <div class="row row-space-12">
                                    <div class="col-xs-8">
                                        {{ venta_filtro.fechahora_creacion1 }}
                                    </div>
                                    <div class="col-xs-8">
                                        {{ venta_filtro.fechahora_creacion2 }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Total</label>
                                <div class="row row-space-12">
                                    <div class="col-xs-8">
                                        {{ venta_filtro.total1 }}
                                    </div>
                                    <div class="col-xs-8">
                                        {{ venta_filtro.total2 }}
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                        <button type="submit" class="btn btn-success">Filtrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


        <!-- #modal-dialog -->
    <div class="modal fade" id="modal-crear">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="/ventas/venta/add" method="POST">{% csrf_token %}
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Crear Venta</legend>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Cliente</label>
                                {{ venta_create.cliente }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Sucursal</label>
                                {{ venta_create.sucursal }}
                            </div>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                        <button type="submit" class="btn btn-success">Crear</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div style="display: none;">
        <form method="post" id="reporte" action="{% url 'ventas:ventas_reporte' %}">{% csrf_token %}
            <div class="modal-body">
                <fieldset>
                    <legend class="m-b-15">Filtros</legend>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Cliente</label>
                        {{ venta_filtro.cliente }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Sucursal</label>
                        {{ venta_filtro.sucursal }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Estado</label>
                        {{ venta_filtro.estado }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tipo Pago</label>
                        {{ venta_filtro.tipo_pago }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Estado Pago</label>
                        {{ venta_filtro.tipo_pago }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Fechas</label>
                        <div class="row row-space-12">
                            <div class="col-xs-8">
                                {{ venta_filtro.fechahora_creacion1 }}
                            </div>
                            <div class="col-xs-8">
                                {{ venta_filtro.fechahora_creacion2 }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Total</label>
                        <div class="row row-space-12">
                            <div class="col-xs-8">
                                {{ venta_filtro.total1 }}
                            </div>
                            <div class="col-xs-8">
                                {{ venta_filtro.total2 }}
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                <button type="submit" class="btn btn-success">Filtrar</button>
            </div>
        </form>


    </div>
{% endblock %}

{% block bottom_scripts %}
    <script src="{% static "assets/plugins/DataTables/media/js/jquery.dataTables.js" %}"></script>
	<script src="{% static "assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js" %}"></script>
    <script src="{% static "assets/plugins/select2/dist/js/select2.min.js" %}"></script>
    <script src="{% static "assets/plugins/bootstrap-daterangepicker/moment.js" %}"></script>
    <script src="{% static "assets/plugins/bootstrap-eonasdan-datetimepicker/build/js/bootstrap-datetimepicker.min.js" %}"></script>
    <script>
        $('#table').DataTable({
            language: {
                "url": "/static/assets/plugins/DataTables/language/Spanish.json"
            },
            responsive: true
        });
        $("#cliente").val('');
        $(".default-select2").select2({placeholder: 'Seleccione'});
        $(".multiple-select2").select2();
        $(".select2-container--default").removeAttr('style').css("width","100%");
        $('#fechahora_creacion1').datetimepicker({format:'DD/MM/YYYY HH:mm'});
        $('#fechahora_creacion2').datetimepicker({format:'DD/MM/YYYY HH:mm'});
        $("#fechahora_creacion1").on("dp.change", function (e) {
            $('#fechahora_creacion2').data("DateTimePicker").minDate(e.date);
        });
        $("#fechahora_creacion2").on("dp.change", function (e) {
            $('#fechahora_creacion1').data("DateTimePicker").maxDate(e.date);
        });

    </script>
{% endblock %}