almacen/urls.py
# urls.py
from django.urls import path
from almacen.views import StockView, KardexView, RecepcionCompraListView, RecepcionCompraEditView,\
    EntregaVentaListView, EntregaVentaEditView, reporte_stock, KardexReportView, CambiarStockView

app_name = 'reportes'


urlpatterns = [
    path('stock/', StockView.as_view()),
    path('stock_cambio/', CambiarStockView.as_view()),
    path('kardex/', KardexView.as_view()),
    path('recepcion_compra/', RecepcionCompraListView.as_view()),
    path('recepcion_compra/<int:pk>/', RecepcionCompraEditView.as_view()),
    path('entrega_venta/', EntregaVentaListView.as_view()),
    path('entrega_venta/<int:pk>/', EntregaVentaEditView.as_view()),
    path('stockreporte/', reporte_stock, name='stockreporte'),
    path('kardexreport/', KardexReportView, name='kardexreport'),
]

empower/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maestro/', include('maestro.urls')),
    path('almacen/', include('almacen.urls')),
    path('compras/', include('compras.urls')),
    path('clientes/', include('clientes.urls')),
    path('ventas/', include('ventas.urls')),
    path('finanzas/', include('finanzas.urls')),
]

ventas/urls.py
# urls.py
from django.urls import path
from ventas.views import OfertaListView, OfertaEditView, OfertaDetailView, VentaListView, VentaCreateView,\
    VentaEditView, VentaDetailView, ReporteVentas, VentaEntregaView, VentaCancelarView, VentaDuplicarView,\
    VentaFindView, VentaDescuentoAdicionalView, ReportVentas
from ventas.rviews import ProductoDetailsView, ValidarStockView

app_name = 'ventas'

urlpatterns = [
    path('oferta', OfertaListView.as_view()),
    path('oferta/<int:pk>/', OfertaDetailView.as_view()),
    path('oferta/<int:pk>/edit', OfertaEditView.as_view()),
    path('venta', VentaListView.as_view()),
    path('venta/add', VentaCreateView.as_view()),
    path('find', VentaFindView.as_view()),
    path('venta/<int:pk>/edit', VentaEditView.as_view()),
    path('venta/<int:pk>/', VentaDetailView.as_view()),
    path('venta/<int:venta>/entrega', VentaEntregaView.as_view()),
    path('venta/<int:venta>/cancelar', VentaCancelarView.as_view()),
    path('venta/<int:venta>/duplicar', VentaDuplicarView.as_view()),
    path('detalleventa/<int:pk>/descuento', VentaDescuentoAdicionalView.as_view()),
    path('reporteventas/<int:id>', ReporteVentas, name='reporteventas'),
    path('ventas_reporte/', ReportVentas, name='ventas_reporte'),

    path('api/productodetails/<str:producto>/<int:sucursal>', ProductoDetailsView.as_view()),
    path('api/validatestock/<int:presentacion>/<int:sucursal>/<int:cantidad>', ValidarStockView.as_view()),

]

almacen/models.py
from django.db import models
from maestro.models import Producto, Almacen, TipoComprobante
from compras.models import DetalleCompra, DetalleNotaCredito
from ventas.models import DetalleVenta


# Create your models here.
class Stock(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    almacen = models.ForeignKey(Almacen, on_delete=models.CASCADE)


class Kardex(models.Model):
    TIPO_MOVIMIENTO_CHOICES = (
        (1, 'ENTRADA'),
        (2, 'SALIDA')
    )
    TIPO_DETALLE_CHOICES = (
        (1, 'COMPRA'),
        (2, 'VENTA'),
        (3, 'REEMBOLSO COMPRA'),
        (4, 'REEMBOLSO VENTA'),
        (5, 'CONSIGNA PEDIDO')
    )

    almacen = models.ForeignKey(Almacen, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT)
    tipo_movimiento = models.CharField(max_length=1, choices=TIPO_MOVIMIENTO_CHOICES)
    tipo_detalle = models.CharField(max_length=1, choices=TIPO_DETALLE_CHOICES)
    cantidad = models.IntegerField()
    cantidad_entrada = models.IntegerField(blank=True, null=True)
    cantidad_salida = models.IntegerField(blank=True, null=True)
    precio_unitario_entrada = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    precio_unitario_salida = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    total_entrada = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    total_salida = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    cantidad_saldo = models.IntegerField()
    precio_unitario_saldo = models.DecimalField(max_digits=8, decimal_places=2)
    total_saldo = models.DecimalField(max_digits=8, decimal_places=2)
    detallecompra = models.ForeignKey(DetalleCompra, on_delete=models.PROTECT, blank=True, null=True)
    detalleventa = models.ForeignKey(DetalleVenta, on_delete=models.PROTECT, blank=True, null=True)
    detallenota = models.ForeignKey(DetalleNotaCredito, on_delete=models.PROTECT, blank=True, null=True)
    fechahora = models.DateTimeField(auto_now_add=True)
    tipo_comprobante = models.ForeignKey(TipoComprobante, on_delete=models.PROTECT, null=True, blank=True)
    serie_comprobante = models.CharField(max_length=10, null=True, blank=True)
    numero_comprobante = models.CharField(max_length=10, null=True, blank=True)

almacen/views.py
from django.views.generic import ListView, DetailView, RedirectView
from django.db.models import Sum
from django.shortcuts import redirect, HttpResponse


# Model import-->
from maestro.models import Almacen, Sucursal, Categoria, Proveedor, Producto
from .models import Stock, Kardex
from compras.models import Compra, DetalleCompra
from ventas.models import Venta, DetalleVenta
from openpyxl import Workbook,load_workbook
from openpyxl.writer.excel import save_virtual_workbook
from openpyxl.styles import Border, Side
# Model import<--

# Form import-->
from compras.forms import DetalleCompraRecepcionForm, DetalleCompraNoDeseadoForm, CompraRecepcionForm
from almacen.forms import StockFiltroForm, KardexFiltroForm, RecepcionFiltroForm, KardexReportFiltroForm,\
    StockCambioForm
from ventas.forms import VentaEntregaForm, DetalleVentaEntregaForm
# Form import<--

# Utils import-->
from compras.utils import fill_data_detallecompra, crear_nota_credito
from almacen.utils import loadtax, loadstockdetail
from ventas.utils import fill_data_detalleventa
from maestro.utils import empresa_list
# Utils import<--

# Extra python features-->
from datetime import datetime
# Extra python features<--

# Extra python features-->
from maestro.mixin import BasicEMixin
# Extra python features<--
# Create your views here.


class StockView(BasicEMixin, ListView):

    template_name = 'almacen/stock.html'
    model = Stock
    nav_name = 'nav_stock'
    view_name = 'stock'
    action_name = 'leer'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stock_filtro'] = StockFiltroForm(self.request.GET, user=self.request.user)
        context['stock_cambio'] = StockCambioForm()
        return context

    def get_queryset(self):
        sucursal = self.request.GET.getlist('sucursal')
        almacen = self.request.GET.getlist('almacen')
        categoria = self.request.GET.getlist('categoria')
        if len(sucursal) > 0:
            query = Stock.objects.filter(almacen__sucursal__in=Sucursal.objects.filter(pk__in=sucursal))
        elif len(almacen) > 0:
            query = Stock.objects.filter(almacen__in=Almacen.objects.filter(pk__in=almacen))
        else:
            query = Stock.objects.all()
        if len(categoria) > 0:
            query = query.filter(producto__categorias__in=categoria)
        query = query.filter(almacen__sucursal__empresa__in=empresa_list(self.request.user))
        query = loadstockdetail(query.values('producto__descripcion', 'producto__id').annotate(Sum('cantidad')))
        return query


class CambiarStockView(RedirectView):

    url = '/almacen/stock/'
    view_name = 'almacen'
    action_name = 'set_stock'

    def get_redirect_url(self, *args, **kwargs):
        form = StockCambioForm(self.request.POST)
        if form.is_valid():
            try:
                producto = Producto.objects.get(descripcion=form.cleaned_data['producto'])
                stock = Stock.objects.get(producto=producto, almacen=1)
                kardex = Kardex.objects.filter(producto=producto, almacen=1)
                diferencia = stock.cantidad - form.cleaned_data['stock']
                stock.cantidad -= diferencia
                stock.save()
                for k in kardex:
                    k.cantidad_saldo -= diferencia
                    k.total_saldo = k.cantidad_saldo*k.precio_unitario_saldo
                    k.save()
            except Producto.DoesNotExist:
                pass
            url = '/almacen/stock/'
        else:
            url = '/almacen/stock/'
        return url


class KardexView(BasicEMixin, ListView):

    template_name = 'almacen/kardex.html'
    model = Kardex
    nav_name = 'nav_kardex'
    view_name = 'stock'
    action_name = 'leer'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kardex_filtro'] = KardexFiltroForm(self.request.GET, user=self.request.user)
        context['kardex_report'] = KardexReportFiltroForm(self.request.GET, user=self.request.user)
        return context

    def get_queryset(self):
        sucursal = self.request.GET.getlist('sucursales')
        almacen = self.request.GET.getlist('almacenes')
        categoria = self.request.GET.getlist('categorias')
        tipo = self.request.GET.getlist('tipo')
        if len(sucursal) > 0:
            query = Kardex.objects.filter(almacen__sucursal__in=Sucursal.objects.filter(pk__in=sucursal))
        elif len(almacen) > 0:
            query = Kardex.objects.filter(almacen__in=Almacen.objects.filter(pk__in=almacen))
        else:
            query = Kardex.objects.all()
        if len(categoria) > 0:
            query = query.filter(producto__categorias__in=categoria)
        if len(tipo) > 0:
            query = query.filter(tipo_movimiento__in=tipo)
        if 'fecha_inicio' in self.request.GET and 'fecha_fin' in self.request.GET:
            if self.request.GET['fecha_inicio'] != '' and self.request.GET['fecha_fin'] != '':
                fecha_inicio = datetime.strptime(self.request.GET['fecha_inicio'], '%d/%m/%Y %H:%M')
                fecha_fin = datetime.strptime(self.request.GET['fecha_fin'], '%d/%m/%Y %H:%M')
                query = query.filter(fechahora__gte=fecha_inicio, fechahora__lte=fecha_fin)
        query = query.filter(almacen__sucursal__empresa__in=empresa_list(self.request.user))
        query.order_by('fechahora')
        return query


class RecepcionCompraListView(BasicEMixin, ListView):

    template_name = 'almacen/recepcion_compra-list.html'
    model = Compra
    nav_name = 'nav_recepcion_compra'
    view_name = 'recepcion_compra'
    action_name = 'leer'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recepcion_filtro'] = RecepcionFiltroForm(self.request.GET, user=self.request.user)
        return context

    def get_queryset(self):
        proveedores = self.request.GET.getlist('proveedor')
        query = Compra.objects.filter(tipo='2', estado='2')
        if len(proveedores) > 0:
            query = query.filter(proveedor__in=proveedores)
        query = query.filter(proveedor__empresa__in=empresa_list(self.request.user))
        return query


class RecepcionCompraEditView(BasicEMixin, DetailView):

    template_name = 'almacen/recepcion_compra-edit.html'
    model = Compra
    nav_name = 'nav_recepcion_compra'
    view_name = 'recepcion_compra'
    action_name = 'editar'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        detalle_compra = DetalleCompra.objects.filter(compra=self.kwargs['pk'])
        for d in detalle_compra:
            d = loadtax(d)
        context['detalle'] = detalle_compra
        context['compra_form'] = CompraRecepcionForm(instance=context['object'])
        context['clean_form'] = DetalleCompraNoDeseadoForm(proveedor=context['object'].proveedor_id)
        return context

    def post(self, request, *args, **kwargs):
        compra = Compra.objects.get(pk=self.kwargs['pk'])
        form = CompraRecepcionForm(request.POST, instance=compra)
        incidencia = ''
        if form.is_valid():
            compra = form.save()
            if request.POST['detallecompra_to_save'] != '':
                total_final = 0
                flete = 0
                total_inc_flete = 0
                for i in request.POST['detallecompra_to_save'].split(','):
                    if 'dc'+i+'-id' in self.request.POST:
                        if self.request.POST['dc'+i+'-id'] != '':
                            dc = DetalleCompra.objects.get(pk=self.request.POST['dc'+i+'-id'])
                            dc_form = DetalleCompraRecepcionForm(request.POST, instance=dc, prefix='dc'+i)
                        else:
                            dc_form = DetalleCompraNoDeseadoForm(request.POST, prefix='dc'+i,
                                                                 proveedor=compra.proveedor_id)
                    if dc_form.is_valid():
                        dc_obj = dc_form.save(commit=False)
                        dc_obj.compra = compra
                        fill_data_detallecompra(dc_obj, compra.estado, compra)
                        total_final += dc_obj.total_final
                        flete += dc_obj.flete
                        total_inc_flete += (dc_obj.total_final + dc_obj.flete)
                compra.total_final = total_final
                compra.total_inc_flete = total_inc_flete
                compra.flete = flete
                compra.save()
                if compra.estado == '3':
                    incidencia = crear_nota_credito(compra)
            if request.POST['detallecompra_to_delete'] != '':
                for j in request.POST['detallecompra_to_delete'].split(','):
                    detalle_compra = DetalleCompra.objects.get(pk=j)
                    if detalle_compra.is_nodeseado:
                        detalle_compra.delete()
            if compra.estado == '3':
                return redirect('/compras/compra/' + str(compra.id) + incidencia)
            else:
                return redirect('/almacen/recepcion_compra/')
        else:
            return HttpResponse(form.errors)


class EntregaVentaListView(BasicEMixin, ListView):

    template_name = 'almacen/entrega_venta-list.html'
    model = Compra
    nav_name = 'nav_entrega_venta'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entrega_filtro'] = RecepcionFiltroForm(self.request.GET)
        return context

    def get_queryset(self):
        clientes = self.request.GET.getlist('cliente')
        query = Venta.objects.filter(tipo='2', estado='2')
        if len(clientes) > 0:
            query = query.filter(cliente__in=clientes)
        return query

almacen/templates/almacen/kardex.html
{% extends "almacen/base.html" %}
{% load static %}

{% block head_files %}
    <link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />
	<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/plugins/bootstrap-eonasdan-datetimepicker/build/css/bootstrap-datetimepicker.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/css/default/own_replace.css" %}" rel="stylesheet" />
{% endblock %}
{% block content %}
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#modal-filtros" data-toggle="modal" class="btn btn-xs btn-primary"><i class="fa fa-search fas"></i></a>&nbsp;&nbsp;
                <a href="#modal-producto" data-toggle="modal" class="btn btn-xs btn-success"><i class="far fa-lg  fa-file-excel"></i></a>
            </div>
            <h4 class="panel-title">Kardex</h4>
        </div>
        <div class="panel-body">
                <div class="row buttons-content">
                        
                </div>
            <table id="table" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th class="text-nowrap">#</th>
                        <th class="text-nowrap">Fecha Hora</th>
                        <th class="text-nowrap">Producto</th>
                        <th class="text-nowrap">Tipo</th>
                        <th class="text-nowrap">Cantidad</th>
                        <th class="text-nowrap">Almacen</th>
                    </tr>
                </thead>
                <tbody>
                    {% for k in object_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ k.fechahora|date:'d-m-Y H:i' }}</td>
                            <td>{{ k.producto.descripcion }}</td>
                            <td>{% if k.tipo_movimiento == '1' %}ENTRADA{% else %}SALIDA{% endif %}</td>
                            <td>{{ k.cantidad }}</td>
                            <td>{{ k.almacen.descripcion }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block modal %}
        <!-- #modal-dialog -->
    <div class="modal fade" id="modal-filtros">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="">
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Filtros</legend>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Sucursal</label>
                                {{ kardex_filtro.sucursal }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Almacen</label>
                                {{ kardex_filtro.almacen }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Categorias</label>
                                {{ kardex_filtro.categoria }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tipo de Movimiento</label>
                                {{ kardex_filtro.tipo }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Fechas</label>
                                <div class="row row-space-12">
                                    <div class="col-xs-8">
                                        {{ kardex_filtro.fecha_inicio }}
                                    </div>
                                    <div class="col-xs-8">
                                        {{ kardex_filtro.fecha_fin }}
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                        <button type="submit" class="btn btn-success">Filtrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal-producto">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4>REPORTE KARDEX</h4>
                </div>
                <form method="POST" action="{% url 'reportes:kardexreport'%}" >{% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group row m-b-5">
                            <div class="col-md-2">
                                <label class="control-label">Producto</label>
                            </div>
                            <div class="col-md-4">
                               {{ kardex_report.productos }}
                            </div>
                            <div class="col-md-2">
                                <label class="control-label">Sucursal</label>
                            </div>
                            <div class="col-md-4">
                               {{ kardex_report.sucursal }}
                            </div>

                        </div>

                        <div class="form-group row m-b-2">
                            <div class="col-md-2">
                                <label>Fechas</label>
                            </div>
                            <div class="col-md-10">
                                <div class="input-group">
                                    {{ kardex_report.date_inicio }}
                                    <span class="input-group-addon"></span>
                                    {{ kardex_report.date_fin }}
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">

                            <button type="submit" class="btn btn-xs btn-success" >Reporte</button>

                        </div>
                    </div>

                </form>
            </div>

        </div>


    </div>
{% endblock %}

{% block bottom_scripts %}
    <script src="{% static "assets/plugins/DataTables/media/js/jquery.dataTables.js" %}"></script>
	<script src="{% static "assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js" %}"></script>
    <script src="{% static "assets/plugins/select2/dist/js/select2.min.js" %}"></script>
    <script src="{% static "assets/plugins/bootstrap-daterangepicker/moment.js" %}"></script>
    <script src="{% static "assets/plugins/bootstrap-eonasdan-datetimepicker/build/js/bootstrap-datetimepicker.min.js" %}"></script>
    <script>
        $('#table').DataTable({
            language: {
                "url": "/static/assets/plugins/DataTables/language/Spanish.json"
            },
            responsive: true
        });
        $(".multiple-select2").select2();
         $(".default-select2").select2();
        $(".sel2").select2();
        $('#fecha_inicio').datetimepicker({format:'DD/MM/YYYY HH:mm'});
        $('#fecha_fin').datetimepicker({format:'DD/MM/YYYY HH:mm'});
        $("#fecha_inicio").on("dp.change", function (e) {
            $('#fecha_fin').data("DateTimePicker").minDate(e.date);
        });
        $("#fecha_fin").on("dp.change", function (e) {
            $('#fecha_inicio').data("DateTimePicker").maxDate(e.date);
        });
         $('#date_inicio').datetimepicker({format:'DD/MM/YYYY HH:mm'});
        $('#date_fin').datetimepicker({format:'DD/MM/YYYY HH:mm'});
        $("#date_inicio").on("dp.change", function (i) {
        $('#date_fin').data("DateTimePicker").minDate(i.date);
        });
        $("#date_fin").on("dp.change", function (i) {
            $('#date_inicio').data("DateTimePicker").maxDate(i.date);
        });
        $(".select2-container--default").removeAttr('style').css("width","100%");
    </script>
{% endblock %}

almacen/templates/almacen/stock.html
{% extends "almacen/base.html" %}
{% load static %}

{% block head_files %}
    <link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />
	<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/css/default/own_replace.css" %}" rel="stylesheet" />
{% endblock %}
{% block content %}
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#modal-filtros" data-toggle="modal" class="btn btn-xs btn-primary"><i class="fa fa-search fas"></i></a>
                &nbsp;&nbsp;
                <button type="submit" form="reporte" class="btn btn-xs btn-success buttons"><i class="far fa-file-excel"></i></button>
                
            </div>
            <h4 class="panel-title">Stock</h4>
        </div>
        <div class="panel-body">
            <table id="table" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th class="text-nowrap">Producto</th>
                        <th class="text-nowrap">Cantidad</th>
                        <th class="text-nowrap">Detalles</th>
                        <th class="text-nowrap">Cambiar Stock</th>
                    </tr>
                </thead>
                <tbody>
                    {% for s in object_list %}
                        <tr>
                            <td>{{ s.producto__descripcion }}</td>
                            <td>{{ s.cantidad__sum }}</td>
                            <td>{{ s.stock_detail }}</td>
                            <td><div class="fa-2x"><a data-prod="{{ s.producto__descripcion }}" class="no-link stock_btn" ><i class="fas fa-xs fa-edit icons-table"></i></a></div></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block modal %}
        <!-- #modal-dialog -->
    <div class="modal fade" id="modal-filtros">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="">
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Filtros</legend>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Sucursal</label>
                                {{ stock_filtro.sucursal }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Almacen</label>
                                {{ stock_filtro.almacen }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Categorias</label>
                                {{ stock_filtro.categoria }}
                            </div>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                        <button type="submit" class="btn btn-success">Filtrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

<div style="display: none">
                <form method="POST" id="reporte"  action="{% url 'reportes:stockreporte'%}">{% csrf_token %}
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Reporte de Stock</legend>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Sucursal</label>
                                {{ stock_filtro.sucursal }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Almacen</label>
                               {{ stock_filtro.almacen }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Categorias</label>
                                {{ stock_filtro.categoria }}
                            </div>
                        </fieldset>
                    </div>

                </form>
            </div>


    <!-- #modal-dialog -->
    <div class="modal fade" id="modal-stock">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="post" action="/almacen/stock_cambio/">{% csrf_token %}
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Cambiar Stock</legend>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Nuevo Stock</label>
                                {{ stock_cambio.stock }}
                                {{ stock_cambio.producto }}
                            </div>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                        <button type="submit" class="btn btn-success">Cambiar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block bottom_scripts %}
    <script src="{% static "assets/plugins/DataTables/media/js/jquery.dataTables.js" %}"></script>
	<script src="{% static "assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js" %}"></script>
    <script src="{% static "assets/plugins/select2/dist/js/select2.min.js" %}"></script>
    <script>
        $('#table').DataTable({
            language: {
                "url": "/static/assets/plugins/DataTables/language/Spanish.json"
            },
            responsive: true
        });
        $(".multiple-select2").select2();
        $(".select2-container--default").removeAttr('style').css("width","100%");
        $(".stock_btn").click(function() {

                  $('#modal-stock').modal('show');
                  $('#prod_inp').val(this.getAttribute('data-prod'));
                });
    </script>
{% endblock %}