compras/urls.py
# urls.py
from django.urls import path
from compras.views import CompraListView, CompraCreateView, CompraEditView, CompraDetailView,\
    reporte_orden, CompraEntregaView, CompraCancelarView, NotaCreditoListView, NotaCreditoDetailView,\
    DetalleNotaCreditoConsignaView, NotaCreditoCerrarView
from compras.rviews import ProductosListView, PresentacionxProductoListView, PrecioTentativoView
app_name = 'compras'

urlpatterns = [
    path('compra', CompraListView.as_view()),
    path('compra/add', CompraCreateView.as_view()),
    path('compra/<int:pk>/edit', CompraEditView.as_view()),
    path('compra/<int:compra>/entrega', CompraEntregaView.as_view()),
    path('compra/<int:compra>/cancelar', CompraCancelarView.as_view()),
    path('compra/<int:pk>/', CompraDetailView.as_view()),
    path('notacredito', NotaCreditoListView.as_view()),
    path('notacredito/<int:pk>/', NotaCreditoDetailView.as_view()),
    path('notacredito/<int:pk>/cerrar', NotaCreditoCerrarView.as_view()),
    path('detallenotacredito/<int:detalle_notacredito>/consignar', DetalleNotaCreditoConsignaView.as_view()),
    path('reporteorden/', reporte_orden, name='reporteorden'),

    path('api/productoxproveedor/<int:proveedor>', ProductosListView.as_view()),
    path('api/presentacionxproducto/<str:producto>', PresentacionxProductoListView.as_view()),
    path('api/preciotentativo/<int:pk>', PrecioTentativoView.as_view()),
]

empower/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maestro/', include('maestro.urls')),
    path('almacen/', include('almacen.urls')),
    path('compras/', include('compras.urls')),
    path('clientes/', include('clientes.urls')),
    path('ventas/', include('ventas.urls')),
    path('finanzas/', include('finanzas.urls')),
]

ventas/urls.py
# urls.py
from django.urls import path
from ventas.views import OfertaListView, OfertaEditView, OfertaDetailView, VentaListView, VentaCreateView,\
    VentaEditView, VentaDetailView, ReporteVentas, VentaEntregaView, VentaCancelarView, VentaDuplicarView,\
    VentaFindView, VentaDescuentoAdicionalView, ReportVentas
from ventas.rviews import ProductoDetailsView, ValidarStockView

app_name = 'ventas'

urlpatterns = [
    path('oferta', OfertaListView.as_view()),
    path('oferta/<int:pk>/', OfertaDetailView.as_view()),
    path('oferta/<int:pk>/edit', OfertaEditView.as_view()),
    path('venta', VentaListView.as_view()),
    path('venta/add', VentaCreateView.as_view()),
    path('find', VentaFindView.as_view()),
    path('venta/<int:pk>/edit', VentaEditView.as_view()),
    path('venta/<int:pk>/', VentaDetailView.as_view()),
    path('venta/<int:venta>/entrega', VentaEntregaView.as_view()),
    path('venta/<int:venta>/cancelar', VentaCancelarView.as_view()),
    path('venta/<int:venta>/duplicar', VentaDuplicarView.as_view()),
    path('detalleventa/<int:pk>/descuento', VentaDescuentoAdicionalView.as_view()),
    path('reporteventas/<int:id>', ReporteVentas, name='reporteventas'),
    path('ventas_reporte/', ReportVentas, name='ventas_reporte'),

    path('api/productodetails/<str:producto>/<int:sucursal>', ProductoDetailsView.as_view()),
    path('api/validatestock/<int:presentacion>/<int:sucursal>/<int:cantidad>', ValidarStockView.as_view()),

]

compras/models.py
from django.db import models
from django.contrib.auth.models import User
from maestro.models import Proveedor, PresentacionxProducto, Producto, Almacen, TipoComprobante, Impuesto


# Create your models here.
# Total Final = > Total luego del descuento.
class Compra(models.Model):
    ESTADO_CHOICES = (
        ('1', 'GENERADO'),
        ('2', 'CONVERTIDO A PEDIDO'),
        ('3', 'INGRESADO'),
        ('4', 'ANULADO'),
        # ('5', 'OCUPADO')
    )
    TIPO_CHOICES = (
        ('1', 'COMPRA DIRECTA'),
        ('2', 'PEDIDO'),
    )
    TIPO_PAGO_CHOICES = (
        ('1', 'CONTADO'),
        ('2', 'CREDITO'),
    )
    ESTADO_PAGO_CHOICES = (
        ('1', 'EN DEUDA'),
        ('2', 'PAGADO'),
    )
    asignado = models.ForeignKey(User, on_delete=models.PROTECT)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.PROTECT)
    almacen = models.ForeignKey(Almacen, on_delete=models.PROTECT)
    estado = models.CharField(max_length=1, choices=ESTADO_CHOICES, default='1')
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES, default='2')
    tipo_pago = models.CharField(max_length=1, choices=TIPO_PAGO_CHOICES, default='1')
    estado_pago = models.CharField(max_length=1, choices=ESTADO_PAGO_CHOICES, default='1')
    is_financiado = models.BooleanField(default=False)
    is_entregado = models.BooleanField(default=False)
    fechahora_creacion = models.DateTimeField(auto_now_add=True)
    tipo_comprobante = models.ForeignKey(TipoComprobante, on_delete=models.PROTECT, null=True, blank=True)
    serie_comprobante = models.CharField(max_length=10, null=True, blank=True)
    numero_comprobante = models.CharField(max_length=10, null=True, blank=True)
    sub_total = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    descuento = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    impuesto_monto = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    flete = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    total_final = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    total_inc_flete = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    is_discrepancia = models.BooleanField(default=False)
    guia_remision = models.CharField(max_length=50, blank=True, null=True)


class DetalleCompra(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT)
    presentacionxproducto = models.ForeignKey(PresentacionxProducto, on_delete=models.PROTECT)
    cantidad_presentacion_pedido = models.IntegerField(blank=True, null=True)
    cantidad_presentacion_entrega = models.IntegerField(blank=True, null=True)
    cantidad_unidad_pedido = models.IntegerField(blank=True, null=True)
    cantidad_unidad_entrega = models.IntegerField(blank=True, null=True)
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    sub_total = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    descuento = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    impuesto = models.ManyToManyField(Impuesto)
    impuesto_monto = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    flete = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    total_final = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    total_inc_flete = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    is_oferta = models.BooleanField(default=False)
    is_nodeseado = models.BooleanField(default=True)
    is_checked = models.BooleanField(default=False)
    is_discrepancia = models.BooleanField(default=False)


class OfertaCompra(models.Model):
    TIPO_CHOICES = (
        (1, 'PRODUCTO'),
        (2, 'DESCUENTO MONETARIO'),
        (3, 'DESCUENTO PORCENTUAL'),
    )
    detallecompra = models.ForeignKey(DetalleCompra, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES)
    cantidad_compra = models.IntegerField()
    presentacion_compra = models.ForeignKey(PresentacionxProducto, on_delete=models.PROTECT,
                                            related_name='presentacion_compra')
    retorno = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT, blank=True, null=True)
    presentacion = models.ForeignKey(PresentacionxProducto, on_delete=models.PROTECT,
                                     related_name='presentacion_oferta', blank=True, null=True)


class NotaCredito(models.Model):
    ESTADO_CHOICES = (
        ('1', 'CREADO'),
        ('2', 'COBRADO'),
    )
    estado = models.CharField(max_length=1, choices=ESTADO_CHOICES, default='1')
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    monto = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True, default=0)
    fechahora_creacion = models.DateTimeField(auto_now_add=True)
    fechahora_cierre = models.DateTimeField(blank=True, null=True)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.PROTECT)
    tipo_comprobante = models.ForeignKey(TipoComprobante, on_delete=models.PROTECT, default=4)
    serie_comprobante = models.CharField(max_length=10, null=True, blank=True)
    numero_comprobante = models.CharField(max_length=10, null=True, blank=True)


class DetalleNotaCredito(models.Model):
    TIPO_CHOICES = (
        ('1', 'ENTREGA SOBRECARGADA'),
        ('2', 'ENTREGA INCOMPLETA'),
    )
    ESTADO_CHOICES = (
        ('1', 'PENDIENTE'),
        ('2', 'CONSIGNADO'),
        ('3', 'NOTA CREDITO'),
    )
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES)
    estado = models.CharField(max_length=1, choices=ESTADO_CHOICES, default='1')
    notacredito = models.ForeignKey(NotaCredito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT)
    presentacionxproducto = models.ForeignKey(PresentacionxProducto, on_delete=models.PROTECT)
    cantidad_presentacion_pedido = models.IntegerField(blank=True, null=True)
    cantidad_presentacion_entrega = models.IntegerField(blank=True, null=True)
    cantidad_presentacion_nota = models.IntegerField(blank=True, null=True)
    cantidad_unidad_pedido = models.IntegerField(blank=True, null=True)
    cantidad_unidad_entrega = models.IntegerField(blank=True, null=True)
    cantidad_unidad_nota = models.IntegerField(blank=True, null=True)
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    total = models.DecimalField(max_digits=8, decimal_places=2)

compras/templates/compras/compra-list.html
{% extends "compras/base.html" %}
{% load static %}

{% block head_files %}
    <link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />
	<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/plugins/bootstrap-eonasdan-datetimepicker/build/css/bootstrap-datetimepicker.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet" />
    <link href="{% static "assets/css/default/own_replace.css" %}" rel="stylesheet" />
{% endblock %}


{% block content %}
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#modal-crear" data-toggle="modal" class="btn btn-xs btn-primary buttons"><i class="fa fa-plus"></i></a>
                <a href="#modal-filtros" class="btn btn-xs btn-primary buttons" data-toggle="modal"><i class="fa fa-search"></i></a>&nbsp;

                <button type="submit" form="reporte" class="btn btn-xs btn-success buttons"><i class="far fa-file-excel"></i></button>
               <!--  <a  href="/compras/reportes" id="btnExport" class="btn btn-xs btn-primary buttons no-link"><i class="fa fa-search"></i>Reporte</a>       -->
            </div>
            <h4 class="panel-title">Compras</h4>
        </div>
        <div class="panel-body">
           
            <table id="table" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th class="text-nowrap">Proveedor</th>
                        <th class="text-nowrap">Almacen</th>
                        <th class="text-nowrap">Asignado</th>
                        <th class="text-nowrap">Estado</th>
                        <th class="text-nowrap">Tipo</th>
                        <th class="text-nowrap">Total</th>
                        <th class="text-nowrap">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for o in object_list %}
                        <tr>
                            <td>{{ o.proveedor.descripcion }}</td>
                            <td>{{ o.almacen.descripcion }}</td>
                            <td>{{ o.asignado.username }}</td>
                            <td>{{ o.get_estado_display }}</td>
                            <td>{{ o.get_tipo_display }}</td>
                            <td>{{ o.total_inc_flete }}</td>
                            <td><div class="fa-2x"><a class="no-link" href="/compras/compra/{{ o.id }}"><i class="fas fa-xs fa-eye icons-table"></i></a><a class="no-link" href="/compras/compra/{{ o.id }}/edit"><i  class="fas fa-xs fa-edit icons-table"></i></a></div></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block modal %}
    <!-- #modal-dialog -->
    <div class="modal fade" id="modal-filtros">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="">
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Filtros</legend>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Estados</label>
                                {{ compra_filtro.estado }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Proveedores</label>
                                {{ compra_filtro.proveedor }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Fecha Creación</label>
                                <div class="row row-space-12">
                                    <div class="col-xs-8">
                                        {{ compra_filtro.fechahora_creacion1 }}
                                    </div>
                                    <div class="col-xs-8">
                                        {{ compra_filtro.fechahora_creacion2 }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Monto Total</label>
                                <div class="row row-space-12">
                                    <div class="col-xs-8">
                                        {{ compra_filtro.total_final1 }}
                                    </div>
                                    <div class="col-xs-8">
                                        {{ compra_filtro.total_final2 }}
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                        <button type="submit" class="btn btn-success">Filtrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


        <!-- #modal-dialog -->
    <div class="modal fade" id="modal-crear">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="/compras/compra/add" method="POST">{% csrf_token %}
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Crear Compra</legend>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Proveedor</label>
                                {{ compra_create.proveedor }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Almacen</label>
                                {{ compra_create.almacen }}
                            </div>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                        <button type="submit" class="btn btn-success">Crear</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

     <div style="display: none">

        <form method="POST" id="reporte"  action="{% url 'compras:reporteorden' %}">{% csrf_token %}
            <div class="modal-body">
                <fieldset>
                    <legend class="m-b-15">Reporte de Orden </legend>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Etados</label>
                        {{ orden_filtro.estado }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Proveedores</label>
                        {{ orden_filtro.proveedor }}
                    </div>

                   <div class="form-group">
                            <label for="exampleInputEmail1">Fecha Creación</label>
                            <div class="row row-space-12">
                                <div class="col-xs-8">
                                    {{ compra_filtro.fechahora_creacion1 }}
                                </div>
                                <div class="col-xs-8">
                                    {{ compra_filtro.fechahora_creacion2 }}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Monto Total</label>
                            <div class="row row-space-12">
                                <div class="col-xs-8">
                                    {{ compra_filtro.total_final1 }}
                                </div>
                                <div class="col-xs-8">
                                    {{ compra_filtro.total_final2 }}
                                </div>
                            </div>
                        </div>

                </fieldset>
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                <button type="submit" class="btn btn-success">Reporte</button>
            </div>
        </form>
    </div>
{% endblock %}

{% block bottom_scripts %}
    <script src="{% static "assets/plugins/DataTables/media/js/jquery.dataTables.js" %}"></script>
	<script src="{% static "assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js" %}"></script>
    <script src="{% static "assets/plugins/select2/dist/js/select2.min.js" %}"></script>
    <script src="{% static "assets/plugins/bootstrap-daterangepicker/moment.js" %}"></script>
    <script src="{% static "assets/plugins/bootstrap-eonasdan-datetimepicker/build/js/bootstrap-datetimepicker.min.js" %}"></script>
    <!-- <script src="{% static "assets/own/reporte/tableexcel.js" %}"></script> -->
    <script>
        $('#table').DataTable({
            language: {
                "url": "/static/assets/plugins/DataTables/language/Spanish.json"
            },
            responsive: true
        });
        $(".default-select2").select2();
        $(".multiple-select2").select2();
        $(".select2-container--default").removeAttr('style').css("width","100%");
                $('#fechahora_creacion1').datetimepicker({format:'DD/MM/YYYY HH:mm'});
        $('#fechahora_creacion2').datetimepicker({format:'DD/MM/YYYY HH:mm'});
        $("#fechahora_creacion1").on("dp.change", function (e) {
            $('#fechahora_creacion2').data("DateTimePicker").minDate(e.date);
        });
        $("#fechahora_creacion2").on("dp.change", function (e) {
            $('#fechahora_creacion1').data("DateTimePicker").maxDate(e.date);
        });
    </script>
{% endblock %}

compras/templates/compras/notacredito-detail.html
{% extends "compras/base.html" %}
{% load static %}

{% load maestro_tags %}

{% block head_files %}
        <link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet" >
    <link href="{% static "assets/css/default/own_css.css" %}" rel="stylesheet" >
{% endblock %}

{% block content %}
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                {% if object.estado != '2' %}
                    <a href="#modal-cerrar" data-toggle="modal" class="btn btn-xs btn-danger buttons"><i class="far fa-credit-card"></i></a>
                {% endif %}
            </div>
            <h4 class="panel-title">Nota de Crédito</h4>
        </div>
        <div class="panel-body">

             <div class="form-group row m-b-3">
                    <div class="col-md-2">
                        <label class="control-label">COMPRA:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.compra.id }}
                    </div>
                    <div class="col-md-2">
                        <label class="control-label">PROVEEDOR:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.proveedor.descripcion }}
                    </div>
                    <div class="col-md-2">
                        <label class="control-label">ESTADO:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.get_estado_display }}
                    </div>


                </div>
                <div class="form-group row m-b-3">
                    <div class="col-md-2">
                        <label class="control-label">MONTO:</label>
                    </div>
                    <div class="col-md-2" id="orden_total">
                        {{ object.monto|default_if_none:0 }}
                    </div>

                    <div class="col-md-2">
                        <label class="control-label">FECHA CREACION:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.fechahora_creacion|date:'d-m-Y H:i' }}
                    </div>

                    <div class="col-md-2">
                        <label class="control-label">FECHA CIERRE:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.fechahora_cierre|date:'d-m-Y H:i' }}
                    </div>
                </div>
                        <div class="form-group row m-b-3">
                    <div class="col-md-2">
                        <label class="control-label">TIPO COMPROBANTE:</label>
                    </div>
                    <div class="col-md-2" id="orden_total">
                        {{ object.tipo_comprobante.descripcion }}
                    </div>

                    <div class="col-md-2">
                        <label class="control-label">SERIE:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.serie_comprobante }}
                    </div>

                    <div class="col-md-2">
                        <label class="control-label">NÚMERO:</label>
                    </div>
                    <div class="col-md-2">
                        {{ object.numero_comprobante }}
                    </div>

                </div>
           <div class="col-md-12">
               <legend class="m-b-15">
                   Detalle
               </legend>
               <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th width="15%">Producto</th>
                                <th width="10%">Presentación</th>
                                <th width="10%">Pedido</th>
                                <th width="10%">Recepcionado</th>
                                <th width="10%">Diferencia</th>
                                <th width="10%">Estado</th>
                                <th width="10%">Tipo</th>
                                <th width="10%">Total</th>
                                <th width="15%">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for d in detalle %}
                                    <tr>
                                        <td>{{ d.presentacionxproducto.producto.descripcion }}</td>
                                        <td>{{ d.presentacionxproducto.presentacion.descripcion }}</td>
                                        <td>{{ d.cantidad_presentacion_pedido }}</td>
                                        <td>{{ d.cantidad_presentacion_entrega }}</td>
                                        <td>
                                            {% if d.tipo == '1' %}
                                                Sobrecargo: {{ d.cantidad_presentacion_nota }}
                                            {% else %}
                                                Faltan: {{ d.cantidad_presentacion_nota }}
                                            {% endif %}
                                        </td>
                                        <td>{{ d.get_estado_display }}</td>
                                        <td>{{ d.get_tipo_display }}</td>
                                        <td>{{ d.total }}</td>
                                        <td>
                                            {% if d.tipo == '2' and d.estado != '2' %}
                                                <div class="fa-2x"><a data-id="{{ d.id }}" class="no-link consignar_btn" data-toggle="modal" href="#modal-consigna"><i class="fas fa-xs fa-handshake icons-table"></i></a></div>
                                            {% endif %}
                                        </td>
                                    </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
        </div>
    </div>
    </div>

{% endblock %}


{% block modal %}
    <div class="modal fade" id="modal-consigna">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="form_consigna" action="/compras/detallenotacredito/x/consignar" method="GET">
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Consignar la Entrega del Producto:</legend>
                            <p>¿Se han entregado los productos faltantes?</p>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                        <button type="submit" class="btn btn-success">Consignar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

            <!-- #modal-dialog -->
    <div class="modal fade" id="modal-cerrar">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="form_pago_venta" action="/compras/notacredito/{{ object.id }}/cerrar" method="post">
                    <div class="modal-body">
                        <fieldset>
                            <legend class="m-b-15">Hacer Efectivo la Nota de Crédito:</legend>
                           <div class="form-group">
                                <label for="exampleInputEmail1">Serie:</label>
                                {{ notacredito_form.serie_comprobante }}
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Número:</label>
                                {{ notacredito_form.numero_comprobante }}
                            </div>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                        <button type="submit" class="btn btn-danger">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block bottom_scripts %}
        <script src="{% static "assets/plugins/select2/dist/js/select2.min.js" %}"></script>
    <script src="{% static "assets/own/compras/notacreditodetail.js" %}"></script>

    <script>
        $(".default-select2").select2({placeholder: "Seleccione", dropdownParent: $('#modal-pago')});
        $(".select2-container--default").removeAttr('style').css("width","100%");
            init_detail();

    </script>
{% endblock %}